import { Router } from 'express';
import { requireAdmin } from '../middleware/auth.js';
import { videoConfig, listVideoMedia, createVideoMedia, deleteVideoMedia } from '../controllers/videoMediaController.js';
const router = Router();
router.use(requireAdmin);
router.get('/config', videoConfig);
router.get('/', listVideoMedia);
router.post('/', createVideoMedia);
router.delete('/:id', deleteVideoMedia);
export default router;
